# Generated by Django 2.2 on 2020-07-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='end_trip',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='start_trip',
            new_name='start_date',
        ),
    ]
